# Generated by Django 3.0.1 on 2020-01-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=90)),
                ('email', models.CharField(max_length=100)),
                ('about_product', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
