# Generated by Django 3.0.1 on 2020-01-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_contact_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='load_from',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AddField(
            model_name='orders',
            name='unload_in',
            field=models.CharField(default='', max_length=30),
        ),
    ]
