# Generated by Django 3.0.1 on 2020-01-08 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200108_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='truck_number',
            field=models.CharField(default='', max_length=30),
        ),
    ]
